[package]
name = "wakfu-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["net"] }
tracing = "0.1.40"
wakfu-protocol-macros = { path = "./wakfu-protocol-macros" }
wakfu-buf = { path = "../wakfu-buf" }
