[package]
name = "wakfu-client"
version = "0.1.0"
edition = "2021"

[dependencies]
enumeration = "1.2.2"
env_logger = "0.11.2"
log = "0.4.21"
tokio = { version = "1.36.0", features = ["full"] }
wakfu-protocol = { path = "../wakfu-protocol" }
wakfu-buf = { path = "../wakfu-buf" }
